this notebook will be mainly used for the capstone project.

****************** 
<p> Remark:
<p> REPORTNO have duplication 
    
<p> STATUS  has 4800 unmatched, 188k Matched
    
<P> unmatched matched

****************** 
    
Missing:
SHAPE

SERIOUSINJURIES

FATALITIES

INCDATE

Meta data:
https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Metadata.pdf

In [ ]:
import numpy as np
import pandas as pd

In [25]:
print ("Hello Capstone Project Course!")

Hello Capstone Project Course!

In [22]:
df = pd.read_csv('https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv', sep=',', delimiter=None, header='infer')

In [23]:
pd.set_option('display.max_columns', None)

In [24]:
df.tail(1)

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,LOCATION,EXCEPTRSNCODE,EXCEPTRSNDESC,SEVERITYCODE.1,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,PEDCYLCOUNT,VEHCOUNT,INCDATE,INCDTTM,JUNCTIONTYPE,SDOT_COLCODE,SDOT_COLDESC,INATTENTIONIND,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
194672,1,-122.28936,47.611017,219547,308220,309500,E868008,Matched,Block,NaN,34TH AVE BETWEEN E MARION ST AND E SPRING ST,,NaN,1,Property Damage Only Collision,Rear Ended,2,0,0,2,2018/11/30 00:00:00+00,11/30/2018 3:45:00 PM,Mid-Block (not related to intersection),14,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",NaN,N,Clear,Wet,Daylight,NaN,NaN,NaN,14,From same direction - both going straight - on...,0,0,N

In [9]:
df1=df

In [10]:
df1['EXCEPTRSNCODE'].sort_values(ascending=False)

167975    NEI
134709    NEI
134789    NEI
155327    NEI
134788    NEI
160770    NEI
142640    NEI
183905    NEI
147880    NEI
120450    NEI
147884    NEI
147886    NEI
155315    NEI
120454    NEI
142633    NEI
175052    NEI
120458    NEI
147896    NEI
112447    NEI
112427    NEI
155303    NEI
142629    NEI
155300    NEI
142627    NEI
120466    NEI
147874    NEI
147869    NEI
169179    NEI
169161    NEI
134819    NEI
         ...
116199    NaN
116204    NaN
116214    NaN
116231    NaN
116235    NaN
116255    NaN
116259    NaN
116270    NaN
116292    NaN
116294    NaN
116309    NaN
116320    NaN
116325    NaN
116336    NaN
116367    NaN
116385    NaN
116396    NaN
116400    NaN
116409    NaN
116422    NaN
116425    NaN
116427    NaN
116443    NaN
116464    NaN
116469    NaN
116474    NaN
116508    NaN
116520    NaN
116524    NaN
117373    NaN
Name: EXCEPTRSNCODE, Length: 194673, dtype: object

In [11]:
df.EXCEPTRSNCODE.unique()
#DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)[source]

array([' ', nan, 'NEI'], dtype=object)

In [12]:
df.EXCEPTRSNDESC.unique()

array([nan,
       'Not Enough Information, or Insufficient Location Information'],
      dtype=object)

In [13]:
df["SEGLANEKEY"].sort_values(ascending=False)
df["CROSSWALKKEY"].sort_values(ascending=False)

179239    5239700
190662     703480
155646     701306
154757     701280
159132     701110
162519     700526
171420     700388
170462     699889
168430     699879
175133     699876
169599     699738
164943     699736
167476     699723
151195     699720
170966     699687
171222     699680
162068     696052
149912     678782
152912     668165
152877     664953
161703     664366
164254     664365
194655     650595
178394     642420
157766     642419
167977     642408
181256     642048
180789     638921
157045     638921
187665     638921
           ...
128780          0
128779          0
128778          0
128777          0
128776          0
128775          0
128794          0
128796          0
128817          0
128797          0
128816          0
128815          0
128814          0
128813          0
128812          0
128811          0
128810          0
128809          0
128808          0
128807          0
128806          0
128805          0
128804          0
128803          0
128802          0
128801          0
128800          0
128799          0
128798          0
0               0
Name: CROSSWALKKEY, Length: 194673, dtype: int64

In [14]:
df[df["HITPARKEDCAR"]=="Y"].count()

SEVERITYCODE      7216
X                 7005
Y                 7005
OBJECTID          7216
INCKEY            7216
COLDETKEY         7216
REPORTNO          7216
STATUS            7216
ADDRTYPE          7017
INTKEY             176
LOCATION          7015
EXCEPTRSNCODE     7216
EXCEPTRSNDESC     1264
SEVERITYCODE.1    7216
SEVERITYDESC      7216
COLLISIONTYPE     6916
PERSONCOUNT       7216
PEDCOUNT          7216
PEDCYLCOUNT       7216
VEHCOUNT          7216
INCDATE           7216
INCDTTM           7216
JUNCTIONTYPE      6083
SDOT_COLCODE      7216
SDOT_COLDESC      7216
INATTENTIONIND    1263
UNDERINFL         6918
WEATHER           6880
ROADCOND          6885
LIGHTCOND         6868
PEDROWNOTGRNT        0
SDOTCOLNUM           1
SPEEDING           123
ST_COLCODE        7216
ST_COLDESC        6916
SEGLANEKEY        7216
CROSSWALKKEY      7216
HITPARKEDCAR      7216
dtype: int64

<p><h1>Check aginst the Meta Data</h1>
<p> 
<p><h2>More:</h2>
<p>REPORTNO           object
<p>STATUS             object
<p>SEVERITYCODE        int64
<p>X                 float64
<p>Y                 float64
<p>
    
    
<p><h2>Missing:</h2>
<p>SHAPE
<p><p>SERIOUSINJURIES
<p>FATALITIES
<p>INCDATE 
<p>
<p><h2>Meta data:</h2>
<p>https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Metadata.pdf

In [15]:
df.dtypes

SEVERITYCODE        int64
X                 float64
Y                 float64
OBJECTID            int64
INCKEY              int64
COLDETKEY           int64
REPORTNO           object
STATUS             object
ADDRTYPE           object
INTKEY            float64
LOCATION           object
EXCEPTRSNCODE      object
EXCEPTRSNDESC      object
SEVERITYCODE.1      int64
SEVERITYDESC       object
COLLISIONTYPE      object
PERSONCOUNT         int64
PEDCOUNT            int64
PEDCYLCOUNT         int64
VEHCOUNT            int64
INCDATE            object
INCDTTM            object
JUNCTIONTYPE       object
SDOT_COLCODE        int64
SDOT_COLDESC       object
INATTENTIONIND     object
UNDERINFL          object
WEATHER            object
ROADCOND           object
LIGHTCOND          object
PEDROWNOTGRNT      object
SDOTCOLNUM        float64
SPEEDING           object
ST_COLCODE         object
ST_COLDESC         object
SEGLANEKEY          int64
CROSSWALKKEY        int64
HITPARKEDCAR       object
dtype: object

In [16]:
df[df.duplicated(subset=['REPORTNO'])]

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,LOCATION,EXCEPTRSNCODE,EXCEPTRSNDESC,SEVERITYCODE.1,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,PEDCYLCOUNT,VEHCOUNT,INCDATE,INCDTTM,JUNCTIONTYPE,SDOT_COLCODE,SDOT_COLDESC,INATTENTIONIND,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
2829,1,-122.318958,47.695842,3272,16918,16918,1780512,Matched,Block,NaN,NE 92ND ST BETWEEN 8TH AVE NE AND ROOSEVELT WA...,NaN,NaN,1,Property Damage Only Collision,Parked Car,2,0,0,2,2004/04/25 00:00:00+00,4/25/2004 5:00:00 AM,Mid-Block (not related to intersection),16,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, LEFT SIDE ...",NaN,0,Unknown,Unknown,Unknown,NaN,4116048.0,NaN,32,One parked--one moving,0,0,N
7231,2,-122.355302,47.682178,8981,22777,22777,1782439,Matched,Block,NaN,GREENWOOD AVE N BETWEEN N 73RD ST AND N 74TH ST,NaN,NaN,2,Injury Collision,Rear Ended,8,0,0,4,2004/04/25 00:00:00+00,4/25/2004 10:58:00 AM,Mid-Block (but intersection related),14,"MOTOR VEHICLE STRUCK MOTOR VEHICLE, REAR END",Y,0,Clear,Dry,Daylight,NaN,4116034.0,NaN,14,From same direction - both going straight - on...,0,0,N
11799,2,-122.329047,47.595387,14900,28573,28573,1776526,Matched,Block,NaN,4TH AVE S BETWEEN SEATTLE BLVD S AND I90 WB 4T...,NaN,NaN,2,Injury Collision,Cycles,2,0,1,1,2004/04/21 00:00:00+00,4/21/2004 12:45:00 PM,Driveway Junction,18,"MOTOR VEHICLE STRUCK PEDALCYCLIST, FRONT END A...",NaN,0,Clear,Wet,Daylight,NaN,4112025.0,NaN,45,Vehicle - Pedalcyclist,0,0,N

In [17]:
df[df['REPORTNO']=="1776526"]

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,LOCATION,EXCEPTRSNCODE,EXCEPTRSNDESC,SEVERITYCODE.1,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,PEDCYLCOUNT,VEHCOUNT,INCDATE,INCDTTM,JUNCTIONTYPE,SDOT_COLCODE,SDOT_COLDESC,INATTENTIONIND,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
3647,2,-122.329047,47.595387,4264,12923,12923,1776526,Matched,Block,NaN,4TH AVE S BETWEEN SEATTLE BLVD S AND I90 WB 4T...,NaN,NaN,2,Injury Collision,Cycles,2,0,1,1,2004/04/21 00:00:00+00,4/21/2004 12:45:00 PM,Driveway Junction,18,"MOTOR VEHICLE STRUCK PEDALCYCLIST, FRONT END A...",NaN,0,Clear,Wet,Daylight,NaN,4112025.0,NaN,45,Vehicle - Pedalcyclist,0,0,N
11799,2,-122.329047,47.595387,14900,28573,28573,1776526,Matched,Block,NaN,4TH AVE S BETWEEN SEATTLE BLVD S AND I90 WB 4T...,NaN,NaN,2,Injury Collision,Cycles,2,0,1,1,2004/04/21 00:00:00+00,4/21/2004 12:45:00 PM,Driveway Junction,18,"MOTOR VEHICLE STRUCK PEDALCYCLIST, FRONT END A...",NaN,0,Clear,Wet,Daylight,NaN,4112025.0,NaN,45,Vehicle - Pedalcyclist,0,0,N

In [18]:
df2=df

In [19]:
df2.drop(['X','Y','SEVERITYCODE.1','OBJECTID','INCKEY','COLDETKEY','EXCEPTRSNCODE','EXCEPTRSNDESC'], axis=1, index=None, columns=None, level=None, inplace=True, errors='raise')

In [ ]:
df2.head()

In [26]:
df2.columns

Index(['SEVERITYCODE', 'REPORTNO', 'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION',
       'SEVERITYDESC', 'COLLISIONTYPE', 'PERSONCOUNT', 'PEDCOUNT',
       'PEDCYLCOUNT', 'VEHCOUNT', 'INCDATE', 'INCDTTM', 'JUNCTIONTYPE',
       'SDOT_COLCODE', 'SDOT_COLDESC', 'INATTENTIONIND', 'UNDERINFL',
       'WEATHER', 'ROADCOND', 'LIGHTCOND', 'PEDROWNOTGRNT', 'SDOTCOLNUM',
       'SPEEDING', 'ST_COLCODE', 'ST_COLDESC', 'SEGLANEKEY', 'CROSSWALKKEY',
       'HITPARKEDCAR'],
      dtype='object')

For the FIRST week, you will required to submit the following:

1. A description of the problem and a discussion of the background. (15 marks)

Background:
____________________________________

In this Capstone Project, we will use the 
1. Dataset of the All collisions (car-accidents - 2004 to Present.) in Seattle 
2. the Metadata of the dataset 

provided by SPD and recorded by Traffic Records (seattle.gov) to understand the Car Accident occurred in Seattle. 

The understanding of the data includes studying the factors such as 
- the accident severity, the accident type, the details of the accident, 
- the Transportation (e.g. car / bicycles) and how many people and who involved in the accident 
- the weather, road condition and environmental factors at the point-in-time of the   accident
- the location of the accident, the surrounding physical environment of the location accidents, etc. 

After the understanding, we will start analyzing the accident by using multiple data analytic tools and skills (e.g. pandas) learned in this course, 
to understand the relation between the factors (e.g. correlation, means, frequency, max, min. etc.)

After the data analysis, we will try to draw conclusion and forecast by evaluating the relation of the data in the dataset and drawing hypothesis (model)

And then using the dataset (diving into training data vs sample data) to simulate and test the effectiveness hypothesis (model). 

Finally, we will write a report and resent the observation in a PPT. 

During the project, we will use GitHub Account to upload the changes of the Jupyter notebook of The Project to GitHub to ensure all changes are recorded. 


A description of the problem 
____________________________________

As descripted in the background section, we aim at using the dataset & metadata to 
1. draw conclusion 
2. make prediction 
3. represent the observation, and
4. make practical and meaningful suggestions to the settle gov, 

and hence to reduce the 
1. frequency and 
2. severity of the accident in future. 

in conclusion, we hope to give recommendation to the gov. to make remediation / correction / education at the potential problematic factors (black spots)
in order to prevent / reduce any car accidents in future, and the most importantly, to SAVE LIFE!

2. A description of the data and how it will be used to solve the problem. (15 marks)

A description of the data
----------------------------------------
Through studying the dataset and the meta data, we understand that the following data is are useful, 
 
'REPORTNO', Remarks: new data, some incidents have the same report no. therefore, we keep this data to find duplication. 
'STATUS', Remarks: new data, the status has two type, matched (~188k), unmatched (4800), it helps us to filter the potential incorrect / inaccurate / incomplete data. Since the total no. of unmatched is less than 1 % of the total data. Filtering out the data is acceptable and it is insignificant to the result / conclusion of the data analysis result 

'SEVERITYCODE', A code that corresponds to the severity of the collision:
• 3—fatality
• 2b—serious injury
• 2—injury
• 1—prop damage
• 0—unknown 

'ADDRTYPE', Collision address type:
• Alley
• Block
• Intersection

'INTKEY', Key that corresponds to the intersection associated with a collision 
'LOCATION’, Description of the general location of the collision 

'SEVERITYDESC’, A detailed description of the severity of the collision 

'COLLISIONTYPE’, Collision type
'PERSONCOUNT’, The total number of people involved in the collision 
'PEDCOUNT’, The number of pedestrians involved in the collision. This is entered by the state.
 'PEDCYLCOUNT', The number of bicycles involved in the collision. This is entered by the state. 
'VEHCOUNT’, The number of vehicles involved in the collision. This is entered by the state. 
'INCDATE', The date of the incident. 
'INCDTTM’, The date and time of the incident.
'‘, The of junction at which collision took place 
'SDOT_COLCODE', A code given to the collision by SDOT. 
'SDOT_COLDESC', A description of the collision corresponding to the collision codes. 
'INATTENTIONIND', Whether or not collision was due to inattention. (Y/N) 
'codes or not a driver involved was under the influence of drugs or alcohol. 
'WEATHER', A description of the weather conditions during the time of the collision
'ROADCOND', The condition of the road during the collision. 
'LIGHTCOND’, The light conditions during the collision. 
'PEDROWNOTGRNT', Whether or not the pedestrian right of way was not granted. (Y/N) 
'SPEEDING', Whether or not speeding was a factor in the collision. (Y/N)
'ST_COLCODE’, A code provided by the state that describes the collision.
'ST_COLDESC', A description that corresponds to the state’s coding designation.
'SEGLANEKEY', A key for the lane segment in which the collision occurred. 
'CROSSWALKKEY', A key for the crosswalk at which the collision occurred. 
'HITPARKEDCAR’, Whether or not the collision involved hitting a parked car. (Y/N) 
 
And the data could be categorized into the following groups:
1.- the accident severity, the accident type, the details of the accident, 
 
2.- the Transportation (e.g. car / bicycles) and how many people and who involved in the accident 

3.- the weather, road condition and environmental factors at the point-in-time of the   accident

4. - the location of the accident, the surrounding physical environment of the location accidents, etc. 

5. - irrelevant / duplicated for the capstone project (could be drop)
	'X','Y','SEVERITYCODE.1','OBJECTID','INCKEY','COLDETKEY','EXCEPTRSNCODE','EXCEPTRSNDESC'
	(Potential irrelevant data - 'SDOTCOLNUM', A number given to the collision by SDOT.)

How it will be used to solve the problem
____________________________________

For the FIRST week, you will required to submit the following:
<br>
<p>A description of the problem and a discussion of the background. (15 marks)
<p>A description of the data and how it will be used to solve the problem. (15 marks)
<br>

For the SECOND week, the final deliverables of the project will be:
<br>  
<p>1. A link to your Notebook on your Github repository, showing your code. (15 marks)
<br>  
<p>2. A full report consisting of all of the following components (15 marks):
- Introduction where you discuss the business problem and who would be interested in this project.
- Data where you describe the data that will be used to solve the problem and the source of the data.
- Methodology section which represents the main component of the report where you discuss and describe any exploratory data analysis that you did, any inferential statistical testing that you performed, if any, and what machine learnings were used and why.
- Results section where you discuss the results.
- Discussion section where you discuss any observations you noted and any recommendations you can make based on the - results.
- Conclusion section where you conclude the report. 
<br>

<p>3. Your choice of a presentation or blogpost. (10 marks)
<br>   
Here are examples of previous outstanding submissions that should give you an idea of what your report would look like, what your notebook would look like in terms of clean, clear, and well-commented code, and what your presentation would look like or your blogpost would look like:
<br>   
<P>Report: https://cocl.us/coursera_capstone_report
<P>Notebook: https://cocl.us/coursera_capstone_notebook
<P>Presentation: https://cocl.us/coursera_capstone_presentation
<P>Blogpost: https://cocl.us/coursera_capstone_blogpost
  
<br>